# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Format Lint

on:
  pull_request:
    paths:
      - '**/*.swift'
      - '.swift-format.json'
      - '.github/workflows/swift-format.yml'

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"

      - name: Build swift-format
        run: |
          git clone https://github.com/apple/swift-format.git
          cd swift-format
          swift build -c release
          echo "$(pwd)/.build/release" >> $GITHUB_PATH

      - name: Run swift-format lint (will fail on issues)
        run: |
          swift-format lint --recursive Sources

