jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9" # Or your desired Swift version

      - name: Run swift-format lint
        uses: swift-actions/swift-format@v1
        with:
          # Path to format, relative to your repo root.
          # Adjust if your sources/tests are in different directories.
          paths: "Sources"
          # Exclude paths: Use comma-separated list
          exclude-paths: "Tests/BuilderIOTests/Resources"
          # Action to perform: 'lint' for checking, 'format' for fixing
          mode: "lint"
